#!/bin/bash
#shellcheck disable=SC2155
# /usr/bin/gh config list
# 
# /usr/bin/gh config set editor "/usr/local/bin/jj"
# 
# /usr/bin/gh config set browser "/usr/bin/w3m"
# 
# /usr/bin/gh auth login -p ssh
# 
# /usr/bin/gh status
# 
# git init -b main
# 
# git add .
# 
# git commit -m "Initial commit"
# 
# /usr/bin/gh repo delete Open-Technology-Foundation/md2ansi --yes
# 
# /usr/bin/gh repo create Open-Technology-Foundation/md2ansi --public --add-readme 
# 
# git push -u origin main
# 
# git push origin main
# 
# git remote add origin "git@github.com:Open-Technology-Foundation/md2ansi.git"
# 
# git push origin main
# 
# git add .
# 
# git commit -m 'initial commit'
# 
# git push
# 
# git push -u origin main
# 
# git pull
# 
# git push -u origin main
# 
# git push origin main
# 
# git push --set-upstream origin main
 	set -e
	declare -- repository_dir=Open-Technology-Foundation/md2ansi
	declare -- source_dir=/ai/scripts/lib/md2ansi
 	cd "$source_dir"
	declare -- version=$(head -n1 .version >/dev/null || echo '0.4.20')	
	declare -- gh=/usr/bin/gh 
	declare -- git=$(command -v git)
	declare -i new=0

	if [[ ! -d .git ]]; then
	 	$gh repo delete "$repository_dir" --yes ||true
		#rm -rf .git/*; rmdir .git
		new=1
	 	$git init -b main
	fi
	
 	$git add .
 	$git commit -m "${1:-update $version}"
	if ((new)); then
	 	$gh repo create "$repository_dir" --public
 	fi
 	
