#!/bin/bash

# /usr/bin/gh config list
# 
# /usr/bin/gh config set editor "/usr/local/bin/jj"
# 
# /usr/bin/gh config set browser "/usr/bin/w3m"
# 
# /usr/bin/gh auth login -p ssh
# 
# /usr/bin/gh status
# 
# git init -b main
# 
# git add .
# 
# git commit -m "Initial commit"
# 
# /usr/bin/gh repo delete Open-Technology-Foundation/md2ansi --yes
# 
# /usr/bin/gh repo create Open-Technology-Foundation/md2ansi --public --add-readme 
# 
# git push -u origin main
# 
# git push origin main
# 
# git remote add origin "git@github.com:Open-Technology-Foundation/md2ansi.git"
# 
# git push origin main
# 
# git add .
# 
# git commit -m 'initial commit'
# 
# git push
# 
# git push -u origin main
# 
# git pull
# 
# git push -u origin main
# 
# git push origin main
# 
# git push --set-upstream origin main
 
 
set -e
 
 	cd /ai/scripts/lib/md2ansi/
 	/usr/bin/gh repo delete Open-Technology-Foundation/md2ansi --yes ||true
	rm -rf .git/*; rmdir .git
	
 	git init -b main
 	git add .
 	git commit -m 'Initial commit'
 	/usr/bin/gh repo create Open-Technology-Foundation/md2ansi --public
 	
